// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2LhW8sprycGTr2gIKib1UEM2LoegN68',
    appId: '1:378094993843:web:2e1787e9a4e3fd3f348bc6',
    messagingSenderId: '378094993843',
    projectId: 'workout-7e8f6',
    authDomain: 'workout-7e8f6.firebaseapp.com',
    storageBucket: 'workout-7e8f6.firebasestorage.app',
    measurementId: 'G-WS4RE3Q3GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ykpwXHfix2rQKGORdtFvN2VNGqWBNV8',
    appId: '1:378094993843:android:472daf98d0632430348bc6',
    messagingSenderId: '378094993843',
    projectId: 'workout-7e8f6',
    storageBucket: 'workout-7e8f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWF6DSjB56N-Jwl-fAqV8fnF4AEmpZCnE',
    appId: '1:378094993843:ios:b2b995793a6d7427348bc6',
    messagingSenderId: '378094993843',
    projectId: 'workout-7e8f6',
    storageBucket: 'workout-7e8f6.firebasestorage.app',
    iosBundleId: 'com.example.ptService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWF6DSjB56N-Jwl-fAqV8fnF4AEmpZCnE',
    appId: '1:378094993843:ios:b2b995793a6d7427348bc6',
    messagingSenderId: '378094993843',
    projectId: 'workout-7e8f6',
    storageBucket: 'workout-7e8f6.firebasestorage.app',
    iosBundleId: 'com.example.ptService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi2LhW8sprycGTr2gIKib1UEM2LoegN68',
    appId: '1:378094993843:web:1f430cdf9b768d0f348bc6',
    messagingSenderId: '378094993843',
    projectId: 'workout-7e8f6',
    authDomain: 'workout-7e8f6.firebaseapp.com',
    storageBucket: 'workout-7e8f6.firebasestorage.app',
    measurementId: 'G-4G4XZ49CDW',
  );
}
